//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int Id { get; set; }
        public System.DateTime FechaHoraCita { get; set; }
        public string Comentarios { get; set; }
        public bool Atendido { get; set; }
        public int TutorId { get; set; }
        public int AlumnoId { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Tutor Tutor { get; set; }
    }
}
